### ISSUE TITLE
Cannot find "run polyDFE.txt "

### ISSUE THREAD

**Issue by chenyangkang** [paula-tataru/polyDFE#4]
Hi there,

I cannot find the file named "un polyDFE.txt" described in your tutorial page 9, the first line. Could you tell me where it is?

Thanks! And cheer for your work on DFE!

Yangkang

**Comment by paula-tataru** [comment]
Hi Yangkang,

The tutorial is published as a chapter in the book Statistical Population Genomics:
https://link.springer.com/book/10.1007/978-1-0716-0199-0

All example files from tutorial can be found on the books GitHub page:
https://github.com/StatisticalPopulationGenomics/polyDFE

I will look into adding a more direct link to it or copying the example files to this repository.

Paula

**Comment by chenyangkang** [comment]
Hi Paula,

Thanks for your reply. I just realized that I lost an "r" in my question. It should be "run polyDFE.txt". Just in case anyone is looking at it.

Problem solved.

Yangkang
