### ISSUE TITLE
'list' object cannot be coerced to type 'double'

### ISSUE THREAD

**Issue by AoyueBi** [paula-tataru/polyDFE#6]
Hello Tataru,

Question 1: getModelName function bug.
When I run the Analysis.R and source post-processing R script, there is an error  about  getModelName function on 'list' object cannot be coerced to type 'double' . I donot know how to fix it;

Question 2: Output is not consistent.
I found your output data "central_chimp_A.txt" on chimp <https://github.com/StatisticalPopulationGenomics/polyDFE>  is not consistent with your new version code. When I parseOutput the output on central_chimp_A.txt, I found the Line 3 is "Performing inference on central_chimp_sfs using model A", but In your function extractInfo(){}, I found "pos = findPos('-- Performing inference using model', lines)",  so I guess there need some change in the central_chimp_A.txt Line3.

**Comment by paula-tataru** [comment]
Hi,

The book you linked to uses polyDFE-v1.1, while the newest version of the code is polyDFE-v2.0, hence you should no expect the same output. You can access the code for v1.1 here: https://github.com/paula-tataru/polyDFE/tree/v1.1

Regarding question 1, can you provide a reproducible example?

**Comment by AoyueBi** [comment]
Thank you for your prompt reply. 
Regarding question 1:

a reproducible example： in polyDFE-v2.0 folder, example.R:
###########################
######### summarize the DFE
###########################
getDiscretizedDFE(est[[2]])
getDiscretizedDFE(est[[2]], sRanges = c(-100, -10, -1, 0))
dfe = t(sapply(est, getDiscretizedDFE)) ###对结果进行了转置
dfe = t(sapply(est, getDiscretizedDFE, sRanges = c(-100, -10, -1, 0, 1)))
rownames(dfe) = sapply(est, getModelName)  ################### this line I got error~~~~~~~
colnames(dfe) = toNames(c(-100, -10, -1, 0, 1))
print(dfe)
barplot(dfe, beside = TRUE, legend.text = TRUE)
dfe[which(dfe == 0)] = NA
barplot(dfe, beside = TRUE, log = 'y', col = 1:nrow(dfe))
legend("topright", legend = basename(polyDFEfiles), fill = 1:nrow(dfe))

error info:
rownames(dfe) = sapply(est, getModelName)
Error in FUN(X[[i]], ...) : 
  'list' object cannot be coerced to type 'double'
Called from: FUN(X[[i]], ...)
Browse[1]> 

-----------------------------------------------------------------------
Regarding question 2:
I found the tutorial.pdf file in your polyDFE-v2.0 folder, which gives the chimp example  input, output and the analysis.R script for v1.1.  I found no postprocessing.R for v1.1, so can you make it avaliable for us?  I want to test the pipeline on analysis and plot the result.

Thank you so much!

**Comment by paula-tataru** [comment]
I linked v1.1 in my previous answer, you have everything you need there.

Regarding your example, that is not reproducible, if I were to run that in R it would fail because it doesn't know what est is. I need the full scrip and the input files, if you used something else than the provided examples.

**Comment by AoyueBi** [comment]
Dear Tataru,
Thank you for your reply. I am on a vacation for a long time before. After back I read the tutorial you wrote carefully and I have solved this problem by creating new code.  Thank you a  lot. Now I am plotting the result and trying to analyze it carefully.
