### ISSUE TITLE
Install question

### ISSUE THREAD

**Issue by pengyan19** [paula-tataru/polyDFE#9]
When i install this software, i got these error as follows:
Building target: all
Invoking: GCC C Linker
gcc -o "polyDFE" -LC:/cygwin64/usr/local/lib/ ./src/basinhopping.o ./src/likelihood.o ./src/localoptim.o ./src/parse.o ./src/run.o ./src/simulate.o ./src/transform.o -lm -lgsl -lgslcblas
./src/localoptim.o: In function `set_lnL_df':
/public/home/pengyan/biosoft/polyDFE/src/localoptim.c:580: undefined reference to `gsl_multifit_fdfsolver_dif_df'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

**Comment by paula-tataru** [comment]
It looks like you don't have GSL. Please see the details in the readme.

Note also that precompiled binaries are also provided for polyDFEv2.0
